api-version: 1.16

name: Mapcha
version: 2.2
main: dev.affan.mapcha.Mapcha
description: Map based captcha plugin for your Minecraft server.

permissions:
  mapcha.bypass:
    desciption: Allows you to bypass the captcha.
    default: op
